title: Debojyoti Balial
description: >
  <div style="text-align: left;">
    <img src="/Images2/My_image2.jpg" alt="Professional Headshot" style="width: 80px; height: 80px; border-radius: 50%; margin-bottom: 20px;"/>
  </div>
  <div style="text-align: left;">

    <p style="margin: 10px 0;">
      <img src="Images2/Phone Image.jpg" style="width: 20px; height: 20px; vertical-align: middle; margin-right: 5px;"/> 9073395920
    </p>
    <p style="margin: 10px 0;">
      <img src="Images2/mail.jpg" style="width: 20px; height: 20px; vertical-align: middle; margin-right: 5px;"/> <a href="mailto:dbalial@yahoo.com">dbalial@yahoo.com</a>
    </p>
    <p style="margin: 10px 0;">
      <img src="Images2/Linkedin.png" style="width: 20px; height: 20px; vertical-align: middle; margin-right: 5px;"/> <a href="https://linkedin.com/in/Debojyoti-Balial" target="_blank">linkedin.com/in/Debojyoti-Balial</a>
    </p>
    <p style="margin: 10px 0;">
      <img src="Images2/github-mark.png" style="width: 20px; height: 20px; vertical-align: middle; margin-right: 5px;"/> <a href="https://github.com/Dbalial" target="_blank">github.com/Dbalial</a>
    </p>
    <p style="margin: 10px 0;">
      <img src="Images2/website.jfif" style="width: 20px; height: 20px; vertical-align: middle; margin-right: 5px;"/> <a href="https://Dbalial.github.io" target="_blank">Dbalial.github.io</a>
    </p>
    <p style="margin: 10px 0;">
      <img src="Images2/LOcation.jfif" style="width: 20px; height: 20px; vertical-align: middle; margin-right: 5px;"/> Kolkata, West Bengal
    </p>
  </div>

show_download: true
theme: jekyll-theme-minimal
