title: Debojyoti Balial
logo: /Images2/My_image2.jpg
description: ## **Contact**

* **<img src="Images2/Phone Image.jpg" style="width: 20px; height: 20px; vertical-align: middle; margin-left: 5px;"/>**  9073395920
  
* **<img src="Images2/Linkedin.png" style="width: 20px; height: 20px; vertical-align: middle; margin-left: 5px;"/>**  [linkedin.com/in/Debojyoti-Balial](linkedin.com/in/Debojyoti-Balial)
  
* **<img src="Images2/github-mark.png" style="width: 20px; height: 20px; vertical-align: middle; margin-left: 5px;"/>**  [github.com/Dbalial](github.com/Dbalial)
  
* **<img src="Images2/website.jfif" style="width: 30px; height: 30px; vertical-align: middle; margin-left: 2px;"/>**  Dbalial.github.io
  
* **<img src="Images2/LOcation.jfif" style="width: 20px; height: 20px; vertical-align: middle; margin-left: 5px;"/>**  Kolkata, West Bengal

show_download: true
theme: jekyll-theme-minimal
